use std::collections::HashSet;
use std::path::Path;

use emmylua_parser::{
    LuaAstNode, LuaCallExpr, LuaExpr, LuaIndexKey, LuaLiteralToken, NumberResult, PathTrait,
};
use wax::Pattern;

use crate::{
    AccessorFuncCallMetadata, FileId, GmodClassCallArg, GmodClassCallLiteral,
    GmodScriptedClassCallKind, GmodScriptedClassCallMetadata, InferFailReason, LuaDeclTypeKind,
    LuaType, LuaTypeDecl, LuaTypeDeclId, LuaTypeFlag,
    compilation::analyzer::{lua::LuaAnalyzer, unresolve::UnResolveConstructor},
    db_index::DbIndex,
};

pub(super) fn analyze_call(analyzer: &mut LuaAnalyzer, call_expr: LuaCallExpr) -> Option<()> {
    collect_gmod_scripted_class_call(analyzer, &call_expr);
    collect_gmod_vgui_call(analyzer, &call_expr);
    collect_accessorfunc_annotated_call(analyzer, &call_expr);

    let prefix_expr = call_expr.clone().get_prefix_expr()?;
    if let Ok(expr_type) = analyzer.infer_expr(&prefix_expr) {
        let LuaType::Signature(signature_id) = expr_type else {
            return Some(());
        };
        let signature = analyzer.db.get_signature_index().get(&signature_id)?;
        let is_colon_define = signature.is_colon_define;
        let is_colon_call = call_expr.is_colon_call();
        let param_infos = signature
            .param_docs
            .iter()
            .map(|(idx, param_info)| {
                (
                    *idx,
                    param_info.type_ref.clone(),
                    param_info.get_attribute_by_name("constructor").is_some(),
                )
            })
            .collect::<Vec<_>>();

        for (idx, param_type, is_constructor) in param_infos {
            materialize_str_tpl_class_from_call(
                analyzer,
                &call_expr,
                idx,
                &param_type,
                is_colon_define,
                is_colon_call,
            );

            if is_constructor {
                let unresolve = UnResolveConstructor {
                    file_id: analyzer.file_id,
                    call_expr: call_expr.clone(),
                    signature_id,
                    param_idx: idx,
                };
                analyzer
                    .context
                    .add_unresolve(unresolve.into(), InferFailReason::None);
                return Some(());
            }
        }
    }
    Some(())
}

fn materialize_str_tpl_class_from_call(
    analyzer: &mut LuaAnalyzer,
    call_expr: &LuaCallExpr,
    param_idx: usize,
    param_type: &LuaType,
    is_colon_define: bool,
    is_colon_call: bool,
) {
    let LuaType::StrTplRef(str_tpl) = param_type else {
        return;
    };

    let constraint = match str_tpl.get_constraint() {
        Some(LuaType::Ref(type_decl_id)) => type_decl_id.clone(),
        _ => return,
    };
    let is_class_constraint = analyzer
        .db
        .get_type_index()
        .get_type_decl(&constraint)
        .map(|decl| decl.is_class())
        .unwrap_or(false);
    if !is_class_constraint {
        return;
    }

    let arg_idx = match (is_colon_define, is_colon_call) {
        (true, true) => {
            if param_idx == 0 {
                return;
            }
            param_idx - 1
        }
        _ => param_idx,
    };

    let Some(arg_expr) = call_expr
        .get_args_list()
        .and_then(|args| args.get_args().nth(arg_idx))
    else {
        return;
    };
    let Some(arg_name) = extract_string_literal(&arg_expr) else {
        return;
    };

    let class_name = format!(
        "{}{}{}",
        str_tpl.get_prefix(),
        arg_name,
        str_tpl.get_suffix()
    );
    let class_decl_id = LuaTypeDeclId::global(&class_name);
    let mut created_type_decl = false;
    if analyzer
        .db
        .get_type_index()
        .get_type_decl(&class_decl_id)
        .is_none()
    {
        created_type_decl = true;
        analyzer.db.get_type_index_mut().add_type_decl(
            analyzer.file_id,
            LuaTypeDecl::new(
                analyzer.file_id,
                arg_expr.get_range(),
                class_decl_id.get_simple_name().to_string(),
                LuaDeclTypeKind::Class,
                LuaTypeFlag::AutoGenerated.into(),
                class_decl_id.clone(),
            ),
        );
    }

    if !created_type_decl {
        return;
    }

    let super_type = LuaType::Ref(constraint);
    let has_super = analyzer
        .db
        .get_type_index()
        .get_super_types_iter(&class_decl_id)
        .map(|mut supers| supers.any(|existing_super| existing_super == &super_type))
        .unwrap_or(false);
    if !has_super {
        analyzer.db.get_type_index_mut().add_super_type(
            class_decl_id,
            analyzer.file_id,
            super_type,
        );
    }
}

fn collect_accessorfunc_annotated_call(
    analyzer: &mut LuaAnalyzer,
    call_expr: &LuaCallExpr,
) -> Option<()> {
    let prefix_expr = call_expr.get_prefix_expr()?;

    // Extract function name: handle both `obj.Method(...)` (IndexExpr) and `FuncName(...)` (NameExpr)
    let (func_name, owner_arg_index) = match &prefix_expr {
        LuaExpr::IndexExpr(index_expr) => {
            let name = match index_expr.get_index_key()? {
                LuaIndexKey::Name(name_token) => name_token.get_name_text().to_string(),
                LuaIndexKey::String(string_token) => string_token.get_value().to_string(),
                _ => return None,
            };
            (name, None) // owner comes from prefix
        }
        LuaExpr::NameExpr(name_expr) => {
            let name = name_expr.get_name_text()?.to_string();
            (name, Some(0usize)) // owner is the first argument
        }
        _ => return None,
    };

    if !analyzer
        .db
        .get_accessor_func_index()
        .contains_name(&func_name)
    {
        return None;
    }

    let name_param_index = analyzer
        .db
        .get_accessor_func_index()
        .get_annotations(&func_name)
        .and_then(|annotations| {
            annotations
                .first()
                .map(|annotation| annotation.name_param_index)
        })
        .unwrap_or(0);

    let args_list = call_expr.get_args_list()?;
    let args = args_list.get_args().collect::<Vec<_>>();
    let name_arg = args.get(name_param_index)?;
    let accessor_name = extract_string_literal(name_arg)?;
    if accessor_name.is_empty() {
        return None;
    }

    let call_syntax_id = call_expr.get_syntax_id();
    let name_arg_syntax_id = Some(name_arg.get_syntax_id());

    // Find owner type: from first argument (global call) or from prefix expression (method call)
    let owner_type_id = if let Some(arg_idx) = owner_arg_index {
        let owner_arg = args.get(arg_idx)?;
        find_owner_type_for_prefix(analyzer, owner_arg)?
    } else if let LuaExpr::IndexExpr(index_expr) = &prefix_expr {
        find_owner_type_for_prefix(analyzer, &index_expr.get_prefix_expr()?)?
    } else {
        return None;
    };

    analyzer.db.get_accessor_func_call_index_mut().add_call(
        analyzer.file_id,
        AccessorFuncCallMetadata {
            syntax_id: call_syntax_id,
            owner_type_id,
            accessor_name,
            name_arg_syntax_id,
        },
    );

    Some(())
}

fn extract_string_literal(expr: &LuaExpr) -> Option<String> {
    match expr {
        LuaExpr::LiteralExpr(literal_expr) => match literal_expr.get_literal()? {
            LuaLiteralToken::String(string_token) => Some(string_token.get_value().to_string()),
            _ => None,
        },
        _ => None,
    }
}

fn find_owner_type_for_prefix(
    analyzer: &mut LuaAnalyzer,
    prefix: &LuaExpr,
) -> Option<LuaTypeDeclId> {
    if let Ok(prefix_type) = analyzer.infer_expr(prefix)
        && let Some(type_decl_id) = find_decl_id_from_type(&prefix_type)
    {
        return Some(type_decl_id);
    }

    if let LuaExpr::NameExpr(name_expr) = prefix {
        let name = name_expr.get_name_text()?;
        let type_decl_id = LuaTypeDeclId::global(&name);
        if analyzer
            .db
            .get_type_index()
            .get_type_decl(&type_decl_id)
            .is_some()
        {
            return Some(type_decl_id);
        }
    }

    None
}

fn find_decl_id_from_type(typ: &LuaType) -> Option<LuaTypeDeclId> {
    match typ {
        LuaType::Def(type_decl_id) | LuaType::Ref(type_decl_id) => Some(type_decl_id.clone()),
        LuaType::Instance(instance) => find_decl_id_from_type(instance.get_base()),
        LuaType::TypeGuard(inner) => find_decl_id_from_type(inner),
        _ => None,
    }
}

fn collect_gmod_scripted_class_call(analyzer: &mut LuaAnalyzer, call_expr: &LuaCallExpr) {
    if !analyzer.gmod_enabled {
        return;
    }

    // Inline name check to avoid String allocation per call expression
    let prefix_expr = call_expr.get_prefix_expr();
    let kind = match prefix_expr.as_ref() {
        Some(LuaExpr::NameExpr(name_expr)) => name_expr
            .get_name_token()
            .and_then(|t| GmodScriptedClassCallKind::from_call_name(t.get_name_text())),
        Some(LuaExpr::IndexExpr(index_expr)) => {
            index_expr.get_index_key().and_then(|key| match &key {
                LuaIndexKey::Name(name_token) => {
                    GmodScriptedClassCallKind::from_call_name(name_token.get_name_text())
                }
                LuaIndexKey::String(string_token) => {
                    GmodScriptedClassCallKind::from_call_name(&string_token.get_value())
                }
                _ => None,
            })
        }
        _ => None,
    };

    let Some(kind) = kind else {
        return;
    };

    // AccessorFunc can be used anywhere (VGUI panels, etc.), not just in scripted class scopes.
    // DEFINE_BASECLASS also needs to work outside scripted scopes.
    // Only NetworkVar/NetworkVarElement are entity-specific and require scripted scope.
    if kind != GmodScriptedClassCallKind::DefineBaseClass
        && kind != GmodScriptedClassCallKind::AccessorFunc
        && !analyzer.is_scripted_class_scope
    {
        return;
    }

    let (literal_args, args) = extract_call_args(call_expr);

    analyzer.db.get_gmod_class_metadata_index_mut().add_call(
        analyzer.file_id,
        kind,
        GmodScriptedClassCallMetadata {
            syntax_id: call_expr.get_syntax_id(),
            literal_args,
            args,
        },
    );
}

fn collect_gmod_vgui_call(analyzer: &mut LuaAnalyzer, call_expr: &LuaCallExpr) {
    if !analyzer.gmod_enabled {
        return;
    }

    // Fast path: vgui.Register / derma.DefineControl are always dotted accesses.
    // Skip the expensive get_access_path() for the 99.9% of calls that can't match.
    let Some(LuaExpr::IndexExpr(index_expr)) = call_expr.get_prefix_expr() else {
        return;
    };

    let Some(LuaIndexKey::Name(key_token)) = index_expr.get_index_key() else {
        return;
    };
    let key_name = key_token.get_name_text();
    if key_name != "Register" && key_name != "DefineControl" {
        return;
    }

    // Check the base object: handle both direct (vgui.Register) and nested paths
    let kind = match index_expr.get_prefix_expr() {
        Some(LuaExpr::NameExpr(base)) => {
            let base_name = base.get_name_token().map(|t| t.get_name_text().to_string());
            match base_name.as_deref() {
                Some("vgui") if key_name == "Register" => GmodScriptedClassCallKind::VguiRegister,
                Some("derma") if key_name == "DefineControl" => {
                    GmodScriptedClassCallKind::DermaDefineControl
                }
                _ => return,
            }
        }
        Some(_) => {
            // Nested path like something.vgui.Register - fall back to full path
            let Some(call_path) = call_expr.get_access_path() else {
                return;
            };
            let Some(kind) = GmodScriptedClassCallKind::from_call_path(&call_path) else {
                return;
            };
            kind
        }
        None => return,
    };

    let (literal_args, args) = extract_call_args(call_expr);

    analyzer.db.get_gmod_class_metadata_index_mut().add_call(
        analyzer.file_id,
        kind,
        GmodScriptedClassCallMetadata {
            syntax_id: call_expr.get_syntax_id(),
            literal_args,
            args,
        },
    );
}

/// Pre-compute which files are in the scripted class scope.
/// Compiles glob patterns once and checks all files, avoiding per-file compilation.
pub(in crate::compilation::analyzer) fn compute_scripted_class_files(
    db: &DbIndex,
    file_ids: &[FileId],
) -> HashSet<FileId> {
    let scopes = &db.get_emmyrc().gmod.scripted_class_scopes;
    if scopes.include.is_empty() && scopes.exclude.is_empty() {
        return file_ids.iter().copied().collect();
    }

    // Compile glob patterns once for all files
    let include_patterns: Vec<&str> = scopes.include.iter().map(String::as_str).collect();
    let exclude_patterns: Vec<&str> = scopes.exclude.iter().map(String::as_str).collect();

    let include_glob = if !include_patterns.is_empty() {
        match wax::any(include_patterns) {
            Ok(g) => Some(g),
            Err(err) => {
                log::warn!("Invalid gmod.scriptedClassScopes.include pattern: {err}");
                return file_ids.iter().copied().collect();
            }
        }
    } else {
        None
    };

    let exclude_glob = if !exclude_patterns.is_empty() {
        match wax::any(exclude_patterns) {
            Ok(g) => Some(g),
            Err(err) => {
                log::warn!("Invalid gmod.scriptedClassScopes.exclude pattern: {err}");
                return HashSet::new();
            }
        }
    } else {
        None
    };

    file_ids
        .iter()
        .copied()
        .filter(|file_id| check_file_in_scope(db, *file_id, &include_glob, &exclude_glob))
        .collect()
}

fn check_file_in_scope(
    db: &DbIndex,
    file_id: FileId,
    include_glob: &Option<wax::Any>,
    exclude_glob: &Option<wax::Any>,
) -> bool {
    let Some(file_path) = db.get_vfs().get_file_path(&file_id) else {
        return include_glob.is_none();
    };

    let normalized_path = file_path.to_string_lossy().replace('\\', "/");
    let mut candidate_paths = Vec::new();
    push_path_candidates(&mut candidate_paths, &normalized_path);
    let normalized_lower = normalized_path.to_ascii_lowercase();
    if let Some(lua_idx) = normalized_lower.find("/lua/") {
        let lua_relative_path = normalized_path[lua_idx + 1..].to_string();
        push_path_candidates(&mut candidate_paths, &lua_relative_path);
        if let Some(stripped) = lua_relative_path.strip_prefix("lua/") {
            push_path_candidates(&mut candidate_paths, stripped);
        }
    }
    if let Some(file_name) = file_path.file_name().and_then(|name| name.to_str()) {
        push_candidate_path(&mut candidate_paths, file_name);
    }

    if let Some(include) = include_glob {
        if !candidate_paths
            .iter()
            .any(|path| include.is_match(Path::new(path)))
        {
            return false;
        }
    }

    if let Some(exclude) = exclude_glob {
        if candidate_paths
            .iter()
            .any(|path| exclude.is_match(Path::new(path)))
        {
            return false;
        }
    }

    true
}

fn push_path_candidates(candidate_paths: &mut Vec<String>, path: &str) {
    push_candidate_path(candidate_paths, path);

    let segments = path
        .split('/')
        .filter(|segment| !segment.is_empty())
        .collect::<Vec<_>>();
    for idx in 0..segments.len() {
        push_candidate_path(candidate_paths, &segments[idx..].join("/"));
    }
}

fn push_candidate_path(candidate_paths: &mut Vec<String>, candidate: &str) {
    if candidate.is_empty() {
        return;
    }

    if candidate_paths.iter().any(|existing| existing == candidate) {
        return;
    }

    candidate_paths.push(candidate.to_string());
}

fn extract_call_args(
    call_expr: &LuaCallExpr,
) -> (Vec<Option<GmodClassCallLiteral>>, Vec<GmodClassCallArg>) {
    let Some(args_list) = call_expr.get_args_list() else {
        return (Vec::new(), Vec::new());
    };

    let mut literal_args = Vec::new();
    let mut args = Vec::new();

    for arg_expr in args_list.get_args() {
        let syntax_id = arg_expr.get_syntax_id();
        let value = extract_literal_or_name(&arg_expr);
        literal_args.push(value.clone());
        args.push(GmodClassCallArg { syntax_id, value });
    }

    (literal_args, args)
}

fn extract_literal_or_name(expr: &LuaExpr) -> Option<GmodClassCallLiteral> {
    match expr {
        LuaExpr::LiteralExpr(literal_expr) => match literal_expr.get_literal()? {
            LuaLiteralToken::String(string_token) => Some(GmodClassCallLiteral::String(
                string_token.get_value().to_string(),
            )),
            LuaLiteralToken::Number(number_token) => match number_token.get_number_value() {
                NumberResult::Int(value) => Some(GmodClassCallLiteral::Integer(value)),
                NumberResult::Uint(value) => Some(GmodClassCallLiteral::Unsigned(value)),
                NumberResult::Float(value) => Some(GmodClassCallLiteral::Float(value)),
            },
            LuaLiteralToken::Bool(bool_token) => {
                Some(GmodClassCallLiteral::Boolean(bool_token.is_true()))
            }
            LuaLiteralToken::Nil(_) => Some(GmodClassCallLiteral::Nil),
            _ => None,
        },
        LuaExpr::NameExpr(name_expr) => {
            name_expr.get_name_text().map(GmodClassCallLiteral::NameRef)
        }
        _ => None,
    }
}
